export const GET_CATEGORYS = 'GET_CATEGORYS';
export const GET_ADMIN_CATEGORYS = 'GET_ADMIN_CATEGORYS';
//export const SEARCH_CATEGORY = 'SEARCH_CATEGORY';
//export const SEARCH_CATEGORY_PRODUCT = 'SEARCH_CATEGORY_PRODUCT';
export const SEARCH_CATEGORY_SUCCESS = 'SEARCH_CATEGORY_SUCCESS';
export const GET_CATEGORYS_SUCCESS = 'GET_CATEGORYS_SUCCESS';
export const GET_ADMIN_CATEGORYS_SUCCESS = 'GET_ADMIN_CATEGORYS_SUCCESS';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const CANCEL_GET_CATEGORYS = 'CANCEL_GET_CATEGORYS';
//export const CLEAR_SEARCH_STATE = 'CLEAR_SEARCH_STATE';
//export const SET_LAST_REF_KEY = 'SET_LAST_REF_KEY';


export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_ADMIN_PRODUCTS = 'GET_ADMIN_PRODUCTS';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_CATEGORY_PRODUCT = 'SEARCH_CATEGORY_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const CANCEL_GET_PRODUCTS = 'CANCEL_GET_PRODUCTS';
export const CLEAR_SEARCH_STATE = 'CLEAR_SEARCH_STATE';
export const SET_LAST_REF_KEY = 'SET_LAST_REF_KEY';

export const SET_BASKET_ITEMS = 'SET_BASKET_ITEMS';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const ADD_QTY_ITEM = 'ADD_QTY_ITEM';
export const MINUS_QTY_ITEM = 'MINUS_QTY_ITEM';

export const SET_CHECKOUT_SHIPPING_DETAILS = 'SET_CHECKOUT_SHIPPING_DETAILS';
export const SET_CHECKOUT_PAYMENT_DETAILS = 'SET_CHECKOUT_PAYMENT_DETAILS';
export const RESET_CHECKOUT = 'RESET_CHECKOUT';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const PHONE_SIGNIN = 'PHONE_SIGNIN'
export const PHONE_SIGNUP = 'PHONE_SIGNUP'
export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE';
export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK';
export const SIGNIN_WITH_GITHUB = 'SIGNIN_WITH_GITHUB';
export const ON_AUTHSTATE_CHANGED = 'ON_AUTHSTATE_CHANGED';
export const SET_AUTH_PERSISTENCE = 'SET_AUTH_PERSISTENCE';
export const ON_AUTHSTATE_SUCCESS = 'ON_AUTHSTATE_SUCCESS';
export const ON_AUTHSTATE_FAIL = 'ON_AUTHSTATE_FAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const VERIFICATION_EMAIL = 'VERIFICATION_EMAIL';
export const VERIFICATION_PHONE = 'VERIFICATION_PHONE';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const SET_PROFILE = 'SET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_SHOPS = 'GET_SHOPS';
export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS';
export const CLEAR_SHOPS = 'CLEAR_SHOPS';
export const GET_SHOP_PRODUCTS_SUCCESS = 'GET_SHOP_PRODUCTS_SUCCESS';

export const CREATE_SHOP = 'CREATE_SHOP';
export const CLEAR_SHOP_PROFILE = 'CLEAR_SHOP_PROFILE';
export const SET_SHOP_PROFILE = 'SET_SHOP_PROFILE';	
export const UPDATE_SHOP_PROFILE = 'UPDATE_SHOP_PROFILE';
export const UPDATE_SHOP_PROFILE_SUCCESS = 'UPDATE_SHOP_PROFILE_SUCCESS';
export const GET_SHOP_PRODUCTS = 'GET_SHOP_PRODUCTS';
export const CLEAR_SHOP_PRODUCTS = 'CLEAR_SHOP_PRODUCTS';

export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SET_MIN_PRICE_FILTER = 'SET_MIN_PRICE_FILTER';
export const SET_MAX_PRICE_FILTER = 'SET_MAX_PRICE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const APPLY_FILTER = 'APPLY_FILTER';
export const CLEAR_RECENT_SEARCH = 'CLEAR_RECENT_SEARCH';
export const REMOVE_SELECTED_RECENT = 'REMOVE_SELECTED_RECENT';

export const REGISTER_USER = 'REGISTER_USER';
export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';

export const LOADING = 'LOADING';
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const SET_REQUEST_STATUS = 'SET_REQUEST_STATUS';

export const PLACE_ORDER = 'PLACE_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';

export const ADD_REVIEW = 'ADD_REVIEW';
export const GET_REVIEWS = 'GET_REVIEWS';
export const CLEAR_REVIEWS = 'CLEAR_REVIEWS';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';

export const GET_ADMIN_ADMIN_USERS = 'GET_ADMIN_ADMIN_USERS';
export const CLEAR_ADMIN_ADMIN_USERS = 'CLEAR_ADMIN_ADMIN_USERS';
export const GET_ADMIN_ADMIN_USERS_SUCCESS = 'GET_ADMIN_ADMIN_USERS_SUCCESS';

export const GET_UI_UTILLS = 'GET_UI_UTILLS';
export const GET_UI_UTILLS_SUCCESS = 'GET_UI_UTILLS_SUCCESS';
export const ADD_BANNERS_CHANGE_UI = 'ADD_BANNERS_CHANGE_UI';
export const ADD_BRANDS_CHANGE_UI = 'ADD_BRANDS_CHANGE_UI';
export const ADD_CATEGORIES_CHANGE_UI = 'ADD_CATEGORIES_CHANGE_UI';
export const ADD_SIZES_CHANGE_UI = 'ADD_SIZES_CHANGE_UI';
export const ADD_UI_TO_CLOUD = 'ADD_UI_TO_CLOUD';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';
export const SET_WISHLIST_ITEMS ='SET_WISHLIST_ITEMS';
export const GET_WISHLIST ='GET_WISHLIST';

export const SET_PROMOTER_REFERRAL = 'SET_PROMOTER_REFERRAL';

export const PLACE_PROMOTER_PRODUCT = 'PLACE_PROMOTER_PRODUCT';
export const GET_PROMOTER_PRODUCTS = 'GET_PROMOTER_PRODUCTS';
export const GET_PROMOTER_PRODUCTS_SUCCESS = 'GET_PROMOTER_PRODUCTS_SUCCESS';
export const CLEAR_PROMOTER_PRODUCTS = 'CLEAR_PROMOTER_PRODUCTS';

export const GET_PRODUCTS_MASTER = 'GET_PRODUCTS_MASTER';
export const GET_PRODUCTS_MASTER_SUCCESS = 'GET_PRODUCTS_MASTER_SUCCESS';
export const CLEAR_PRODUCTS_MASTER = 'CLEAR_PRODUCTS_MASTER';
export const REMOVE_PROMOTER_PRODUCT = 'REMOVE_PROMOTER_PRODUCT';
export const REMOVE_PROMOTER_PRODUCT_SUCCESS = 'REMOVE_PROMOTER_PRODUCT_SUCCESS';

export const ADD_SPECIFICATION_TABLE = 'ADD_SPECIFICATION_TABLE';
